In [1]:
import scrapy
import numpy as np

In [6]:
a = [1,2,3,4,5,6,7,8,9,0]
b = np.array(a)
print(a,b)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0] [1 2 3 4 5 6 7 8 9 0]


In [15]:
c = np.array([9,8,7,6,5,4,3])
d = c.copy()
print(c)

[9 8 7 6 5 4 3]


In [8]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [9]:
input("your name")

your namejide


'jide'

In [16]:
d[0] = 998
print(c)

[9 8 7 6 5 4 3]


In [17]:
print(c[:-2])

[9 8 7 6 5]


In [19]:
print(c[-1::-1])

[3 4 5 6 7 8 9]
